// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptkapnxkzzwxhwfnrwsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0a2Fwbnhrenp3eGh3Zm5yd3N4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNjg5NzgsImV4cCI6MjA2OTg0NDk3OH0.2fKnRyhMq6ZSs5oqLQTmQl4KIWZ2CnwKTvFLmjp6-XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});